"""Add final_analysis_summary field to FinalAnalysisResponse

Revision ID: aedb48dd0326
Revises: 01b89ac17a5e
Create Date: 2025-12-01 10:24:53.286331

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aedb48dd0326"
down_revision: Union[str, Sequence[str], None] = "01b89ac17a5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column already exists (defensive for test scenarios)
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("alert_sessions")]

    # Only add column if it doesn't exist
    if "final_analysis_summary" not in columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("alert_sessions", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "final_analysis_summary",
                    sqlmodel.sql.sqltypes.AutoString(),
                    nullable=True,
                )
            )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Check if column exists before trying to drop it
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("alert_sessions")]

    # Only drop column if it exists
    if "final_analysis_summary" in columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("alert_sessions", schema=None) as batch_op:
            batch_op.drop_column("final_analysis_summary")
        # ### end Alembic commands ###
