"""add final_analysis_summary field

Revision ID: 3d5ddcec5d5f
Revises: 01b89ac17a5e
Create Date: 2025-11-25 14:18:59.776600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d5ddcec5d5f"
down_revision: Union[str, Sequence[str], None] = "01b89ac17a5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
