"""add_expected_parallel_count_to_stage_executions

Revision ID: f0dd17b71ce2
Revises: d7e8f9a0b1c2
Create Date: 2025-12-10 13:35:35.702660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0dd17b71ce2"
down_revision: Union[str, Sequence[str], None] = "d7e8f9a0b1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column already exists (defensive for test scenarios)
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("stage_executions")]
    indexes = [idx["name"] for idx in inspector.get_indexes("stage_executions")]

    # Only add column if it doesn't exist
    with op.batch_alter_table("stage_executions", schema=None) as batch_op:
        if "expected_parallel_count" not in columns:
            batch_op.add_column(
                sa.Column("expected_parallel_count", sa.Integer(), nullable=True)
            )
        
        # Drop indexes if they exist (autogenerated cleanup)
        if "ix_stage_executions_parent_stage_execution_id" in indexes:
            batch_op.drop_index(batch_op.f("ix_stage_executions_parent_stage_execution_id"))
        if "ix_stage_executions_session_parent" in indexes:
            batch_op.drop_index(batch_op.f("ix_stage_executions_session_parent"))


def downgrade() -> None:
    """Downgrade schema."""
    # Check if column/indexes exist before trying to recreate/drop them
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("stage_executions")]
    indexes = [idx["name"] for idx in inspector.get_indexes("stage_executions")]

    with op.batch_alter_table("stage_executions", schema=None) as batch_op:
        # Recreate indexes if they don't exist
        if "ix_stage_executions_session_parent" not in indexes:
            batch_op.create_index(
                batch_op.f("ix_stage_executions_session_parent"),
                ["session_id", "parent_stage_execution_id"],
                unique=False,
            )
        if "ix_stage_executions_parent_stage_execution_id" not in indexes:
            batch_op.create_index(
                batch_op.f("ix_stage_executions_parent_stage_execution_id"),
                ["parent_stage_execution_id"],
                unique=False,
            )
        
        # Only drop column if it exists
        if "expected_parallel_count" in columns:
            batch_op.drop_column("expected_parallel_count")
