"""Add interaction_type to LLM interactions

Revision ID: 7c617b3e7c2c
Revises: ae85467a75d2
Create Date: 2025-10-03 12:15:54.424780

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c617b3e7c2c"
down_revision: Union[str, Sequence[str], None] = "ae85467a75d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column already exists (for idempotency with baseline migration)
    from sqlalchemy import inspect
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Get existing columns
    existing_columns = {col['name'] for col in inspector.get_columns('llm_interactions')}
    
    # Only add column if it doesn't exist
    if 'interaction_type' not in existing_columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("llm_interactions", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "interaction_type",
                    sa.String(length=50),
                    server_default="investigation",
                    nullable=False,
                )
            )

        # ### end Alembic commands ###
        
        # Backfill existing records with correct interaction types (only if column was added)
        # Skip if table is empty (optimization)
        result = connection.execute(sa.text("SELECT COUNT(*) FROM llm_interactions"))
        row_count = result.scalar()
        
        if row_count == 0:
            # No records to backfill, skip expensive queries
            return
        
        dialect_name = connection.dialect.name
        
        # Step 1: Identify summarization interactions (simple text search)
        # Check for the specific system message content that only appears in summarization calls
        if dialect_name == 'postgresql':
            # PostgreSQL: Cast JSONB to text for LIKE operator
            connection.execute(sa.text("""
                UPDATE llm_interactions 
                SET interaction_type = 'summarization'
                WHERE CAST(conversation AS text) LIKE '%You are an expert at summarizing technical output%'
            """))
        else:
            # SQLite: conversation is already TEXT
            connection.execute(sa.text("""
                UPDATE llm_interactions 
                SET interaction_type = 'summarization'
                WHERE conversation LIKE '%You are an expert at summarizing technical output%'
            """))
        
        # Step 2: Identify final_analysis interactions (simplified approach)
        # Use simpler text search instead of complex JSON parsing
        if dialect_name == 'postgresql':
            # PostgreSQL: Use simpler JSONB text cast and pattern matching
            # Look for "Final Answer:" in the conversation text (simpler than parsing JSON structure)
            connection.execute(sa.text("""
                UPDATE llm_interactions 
                SET interaction_type = 'final_analysis'
                WHERE interaction_type != 'summarization'
                AND CAST(conversation AS text) LIKE '%Final Answer:%'
            """))
        else:
            # SQLite: Use simpler text search
            connection.execute(sa.text("""
                UPDATE llm_interactions 
                SET interaction_type = 'final_analysis'
                WHERE interaction_type != 'summarization'
                AND conversation LIKE '%Final Answer:%'
            """))
        
        # Step 3: Explicitly set remaining records to 'investigation' (don't rely on default)
        connection.execute(sa.text("""
            UPDATE llm_interactions 
            SET interaction_type = 'investigation'
            WHERE interaction_type NOT IN ('summarization', 'final_analysis')
        """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_interactions", schema=None) as batch_op:
        batch_op.drop_column("interaction_type")

    # ### end Alembic commands ###
