"""add_chat_tables

Revision ID: 11b500f06df2
Revises: da4300b74d0e
Create Date: 2025-11-05 21:22:08.037238

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11b500f06df2'
down_revision: Union[str, Sequence[str], None] = 'da4300b74d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if tables already exist (for idempotency with baseline migration)
    from sqlalchemy import inspect
    connection = op.get_bind()
    inspector = inspect(connection)
    existing_tables = set(inspector.get_table_names())
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'chats' not in existing_tables:
        op.create_table('chats',
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at_us', sa.BIGINT(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mcp_selection', sa.JSON(), nullable=True),
    sa.Column('context_captured_at_us', sa.BIGINT(), nullable=True),
    sa.Column('pod_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_interaction_at', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['alert_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
        )
        with op.batch_alter_table('chats', schema=None) as batch_op:
            batch_op.create_index('ix_chats_created_at', ['created_at_us'], unique=False)
            batch_op.create_index('ix_chats_pod_last_interaction', ['pod_id', 'last_interaction_at'], unique=False)
            batch_op.create_index('ix_chats_session_id', ['session_id'], unique=False)

    if 'chat_user_messages' not in existing_tables:
        op.create_table('chat_user_messages',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at_us', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
        )
        with op.batch_alter_table('chat_user_messages', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_user_messages_chat_id'), ['chat_id'], unique=False)
            batch_op.create_index('ix_chat_user_messages_created_at', ['created_at_us'], unique=False)

    # Add columns to stage_executions table
    # Check if columns already exist
    inspector_cols = inspector.get_columns('stage_executions')
    existing_cols = {col['name'] for col in inspector_cols}
    
    with op.batch_alter_table('stage_executions', schema=None) as batch_op:
        if 'chat_id' not in existing_cols:
            batch_op.add_column(sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if 'chat_user_message_id' not in existing_cols:
            batch_op.add_column(sa.Column('chat_user_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_executions', schema=None) as batch_op:
        batch_op.drop_column('chat_user_message_id')
        batch_op.drop_column('chat_id')

    with op.batch_alter_table('chat_user_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_messages_created_at')
        batch_op.drop_index(batch_op.f('ix_chat_user_messages_chat_id'))

    op.drop_table('chat_user_messages')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('ix_chats_session_id')
        batch_op.drop_index('ix_chats_pod_last_interaction')
        batch_op.drop_index('ix_chats_created_at')

    op.drop_table('chats')
    # ### end Alembic commands ###
